dcgmExporter:
  serviceMonitor:
    enabled: true
devicePlugin:
  env:
  - name: DEVICE_LIST_STRATEGY
    value: cdi-annotations
  - name: CDI_ANNOTATION_PREFIX
    value: cdi.k8s.io/
  - name: NVIDIA_CTK_PATH
    value: /usr/local/nvidia/toolkit/nvidia-ctk
driver:
  enabled: true
toolkit:
  env:
  - name: ACCEPT_NVIDIA_VISIBLE_DEVICES_ENVVAR_WHEN_UNPRIVILEGED
    value: "false"
  - name: CDI_ENABLED
    value: "true"
  - name: NVIDIA_CONTAINER_RUNTIME_MODE
    value: cdi
  - name: NVIDIA_CONTAINER_RUNTIME_MODES_CDI_ANNOTATION_PREFIXES
    value: cdi.k8s.io/
  - name: CRIO_CONFIG_MODE
    value: config
